### ISSUE TITLE
Add hashflag for worng hashtags

### ISSUE THREAD

**Issue by mohammadsadeghforoughi** [seraheazari/MahsaAminiHashflag#1]
It is super useful to add a flag for the wrong hashtags.
(people will alert the writer of the tweet to don't use wrong hashtags)

**Comment by pourdamghani** [comment]
Anything that would not have hashflag will be incorrect. I think it would be messy to also add hashflags for incorrect ones.

**Comment by seraheazari** [comment]
That’s kind of impossible despite the creative ways the regime use to create malicious hashtags, some hashtags have half space in a english one, what regex can find that? Anything that is not flagged is wrong is a better approach I guess.
