### ISSUE TITLE
The exension stopped working

### ISSUE THREAD

**Issue by pourdamghani** [seraheazari/MahsaAminiHashflag#14]
Thanks a lot for developing this great extension.
However, the new version of it has stopped working for me :(
I have tried to instialling again from Chrome webstore and manually, but none worked for me.

I have recived this message before unistalling, or while installing it again from chrome webstore:
"This extension is not trusted by Enhanced Safe Browsing"

Do you have any idea what might be the issue?

**Comment by seraheazari** [comment]
I tried reinstalling the extension from the store in chrome version `106.0.5249.119 (Official Build) (arm64)` and it works fine, However, googling the issue you mentioned, I think you have `Enhanced Safe Browsing` enabled which restricts installing extensions from developers who are not trusted by google developer program policy. I'll try to fix this and become a trusted developer but it might take a few weeks.
You can read more about it and how you can install extension here: 
https://support.google.com/chrome_webstore/answer/2664769?hl=en-GB#zippy=%2Cinstall-with-enhanced-safe-browsing
