### ISSUE TITLE
Add this hashflag for suggestion dropdown so users don't select the wrong hashtags

### ISSUE THREAD

**Issue by mohammadsadeghforoughi** [seraheazari/MahsaAminiHashflag#2]

**Comment by pourdamghani** [comment]
I think this might be challenging, given that the recommendation engine is a separate entity, not sure though. Best to ping twitter again and again to consider these two as official flags.

**Comment by seraheazari** [comment]
That’s kind of impossible despite the creative ways the regime use to create malicious hashtags, some hashtags have half space in a english one, what regex can find that? Anything that is not flagged is wrong is a better approach I guess.

**Comment by seraheazari** [comment]
It’s challenging but I’ll see what I can do.

**Comment by seraheazari** [comment]
This is done now.
