### ISSUE TITLE
Image alignment needs to be fixed

### ISSUE THREAD

**Issue by mahdi** [seraheazari/MahsaAminiHashflag#3]
As shown in the picture posted in this [tweet](https://twitter.com/Hamed/status/1575427606731784192/photo/1), the vertical alignment of the hashflag is not correct. Same for the English hashtag.
![Fd0LC6yXkAILp4X](https://user-images.githubusercontent.com/67627/193015685-46b90fbd-702d-41a2-a9c6-069a7b449b5a.jpeg)

**Comment by seraheazari** [comment]
👍🏻 Will apply a fix.

**Comment by seraheazari** [comment]
applied twitter stylings in the recent commit.
