### ISSUE TITLE
deploy the extention to chrome web store

### ISSUE THREAD

**Issue by arashmilani** [seraheazari/MahsaAminiHashflag#4]
Hi team. Nice idea 👌 
What is the plan to publish this to chrome web store?

**Comment by seraheazari** [comment]
I was hoping that after a day of use we can find any bug or issue then submit it for review in the store. Lets set the deadline for this midnight GMT. The developer account is ready.

**Comment by arashmilani** [comment]
Perfect. I will also look into the issues this afternoon and give a hand to solve them if needed. Again great initiative.

**Comment by seraheazari** [comment]
Submitted the extension for review🤞

**Comment by seraheazari** [comment]
Hashflag is live on chrome store too. updated link in Readme
