### ISSUE TITLE
The hashflag for English hashtags needs to be on the right hand side

### ISSUE THREAD

**Issue by mahdi** [seraheazari/MahsaAminiHashflag#6]
The hashflag on both Persian and English hashtags are shown on the left; while it should be on the right for English ones.

![Screenshot 2022-09-29 at 12 58 14 pm](https://user-images.githubusercontent.com/67627/193025520-a26079e9-5c6f-42cb-8c6c-c2fb3ec98f04.png)

**Comment by seraheazari** [comment]
applied a quick fix, please reload the extension to see if it fixed the issue.
