### ISSUE TITLE
deploy the extention to Mozila Firefox add-ons

### ISSUE THREAD

**Issue by arashmilani** [seraheazari/MahsaAminiHashflag#9]
I created the #8 to fix the Firefox packager. I think we can also publish it to Mozilla Firefox add-ons after this is merged.

**Comment by seraheazari** [comment]
I received message from @mdibaiee that Firefox add-on has been submitted for review, it will hopefully be visible on https://addons.mozilla.org/en-US/firefox/addon/mahsaamini-hashflag/

**Comment by seraheazari** [comment]
The add on is available on Firefox Add Ons store now.

**Comment by arashmilani** [comment]
Great. Can you add a link to it in the README?

**Comment by seraheazari** [comment]
that's already done. 

Our Twitter acc doesn't have many followers so if you could share it would be great.
https://twitter.com/SeraheAzari/status/1575868520163790848
